### PR TITLE
Update signing.md

### PR DESCRIPTION
**Pull request by nitronit**
Added some notes to clarify which set-ups are eligible and why.

## Description

This PR ...

## Checklist

- [x] I have made sure the upstream branch for this PR is correct
- [x] I have made sure this PR is ready to merge
- [x] I have made sure that I have assigned reviewers related to this project

## Changes

- [x] Added ...
- [x] Changed ...
- [ ] Removed ...

## Screenshots

...

## Testing

- Open page ...
- Click ...
- Make sure that ...

## Links/References

- ...
- ...
- ...

## Notes

- ...
- ...
- ...

### CODE REVIEW

**Comment by agouin** [comment]
For the number of horcrux cosigners, we don't actually need an odd number. An even number is a somewhat strange configuration because then you don't really get the advantage of availability like you get with the next odd number. E.g. with threshold 3/4 total, you can still only tolerate only one signer being down (same as 2/3), whereas you can tolerate 2 down by just adding one more cosigner and doing a 3/5. However, a 3/4 is more secure than a 2/3 and a 3/5, so it is still a valid configuration.

**Comment by agouin** [comment]
The raft implementation used by horcrux, `hashicorp/raft`, works fine with an even number of nodes also. Similar to how we require `t > n/2` for threshold signing, raft also requires majority nodes for consensus. So with a 3/4 setup, 3 nodes are required for both raft consensus and also threshold signing. It is an odd configuration but not invalid. The 3/4 configuration can be tested in the horcrux test framework in a test such as `TestChainPureHorcrux` by using the following parameters:
```go
	const signersPerValidator = 4
	const threshold = 3
```

**Comment by nitronit** [comment]
I will close this. 

But I stand "firm" that according to the referenced papers you need an odd number of RAFT nodes.

**Comment by nitronit** [comment]
I will close this. 

But I stand "firm" that according to the referenced papers you need an odd number of RAFT nodes.

**Pull request closed without merging**
